In [180]:
from torchvision.datasets import ImageFolder
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torch.nn.functional as F
from sklearn.preprocessing import OneHotEncoder
import PIL
from PIL import Image
import PIL.Image as pilimg
import torch
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn as nn
import torch.optim.lr_scheduler as lr_scheduler
import torch.optim as optim
import math
import pandas as pd
import numpy as np


import time
from model import Res2Net
from dataloader import data_generator_test

df = pd.read_csv('./result2.csv')
df.columns=['num','path','gt1','gt2','pred','top1','top2','top3','top4','top5']
def label_category(label):
#     category = 0 
    if label == "accomodation" or label == 'village' or label =='residential_neighborhood' or label=='hotel_room' or label =='hallway' or label == 'elevator'or label == 'office': 
        return  1  ##accomd
    elif label == "department_store" or label =='shoppingmall-indoor' or label == 'supermarket': 
        return  2   ## mall
    elif label == "construction_site" or label =='engine_room' or label == 'factory' or label =='construc_facto' or label == 'excavation': 
        return  3  ## construction, factory
    elif label == 'auto_factory':
        return 3
    elif label == "amusement_arcade" or label =='amusement_park' or label == 'aquarium' or label == "art_gallery" or label =='auditorium' : 
        
        return  4 ##여가시설
    elif label == 'bookstore' or label == "library" or label =='movie_theater' or label == 'museum' or label == "swimming_pool" or label == "water_park" : 
        return  4 ##여가시설
    elif label == 'library-indoor' or label =='library-outdoor' or label=='museum-indoor'or label=='museum-outdoor':
        
        return  4 ##여가시설        
    elif label == 'library-indoor' or label =='movie_theater-indoor' or label=='swim-outdoor'or label=='swim-indoor':
        return  4 ##여가시설        
    elif label == "bedroom" or label =='dining_room' or label == 'kitchen'or label == 'living_room':            
        return  5 ##집
    elif label == "dentaloffice" or label =='hospitalroom' or label == 'hospital_room'or label == 'operating_room' or label == 'nursing_home' :            
        return  6
    elif label == "beach" or label == 'broadleaf' or label =='forest_path' or label =='lagoon' or label =='mountain_snowy'or label =='forest_road':
        return  7
    elif label =='lake_natural'or label =='ocean'or label =='raft' or label =='river' or label == 'mountain_path' or label=='lake-natural':
        return  7
    elif label == "classroom" or label =='kindergarden_classroom' or label == 'lecture_room':
        return  8
    elif label == "athletic_field" or label =='football_field' or label == 'golf_course' or label == "gymnasium" or label =='soccer_field' or label == 'stadium':
        return  9
    elif label == "baseball" or label == 'football' or label =='soccer' :
        return  9
    elif label == "crosswalk" or label =='street' :
        return  10
    elif label == "campus" or label =='parking_garage' or label =='parking_lot' or label=='parking-garage-outdoor' or label=='parking-garage-indoor':
        
        
        return  11
    elif label == "campus" or label =='parking_garage' or label =='parking_lot' or label=='parking-garage-outdoor' or label=='parking_garage-indoor' or label=='ambulance' :
        return 11

In [184]:
df

,num,path,gt1,gt2,pred,top1,top2,top3,top4,top5
0,0,./data/val/hallway/capture_2_63.jpg,58,hallway,3,art_gallery,hotel_room,hospital_room,museum-indoor,construction_site
1,1,./data/val/hallway/capture_2_64.jpg,58,hallway,26,hospital_room,kitchen,art_gallery,museum-indoor,aquarium
2,2,./data/val/hallway/capture_2_65.jpg,58,hallway,26,hospital_room,lecture_room,art_gallery,campus,kitchen
3,3,./data/val/hospital_room/capture_3_75.jpg,26,hospital_room,26,hospital_room,hotel_room,construction_site,art_gallery,shoppingmall-indoor
4,4,./data/val/hospital_room/capture_3_58.jpg,26,hospital_room,14,construction_site,art_gallery,campus,hospital_room,supermarket
...,...,...,...,...,...,...,...,...,...,...
295,295,./data/val/bedroom/capture_2_89.jpg,9,bedroom,3,art_gallery,living_room,hotel_room,bookstore,bedroom
296,296,./data/val/bedroom/capture_2_33.jpg,9,bedroom,3,art_gallery,movie_theater,lecture_room,hotel_room,bookstore
297,297,./data/val/bedroom/capture_2_76.jpg,9,bedroom,14,construction_site,hospital_room,art_gallery,museum-indoor,lecture_room
298,298,./data/val/bedroom/capture_2_94.jpg,9,bedroom,28,hotel_room,bookstore,bedroom,art_gallery,construction_site
299,299,./data/val/bedroom/capture_2_49.jpg,9,bedroom,14,construction_site,lecture_room,art_gallery,hospital_room,amusement_park

In [181]:
gt=df['gt2'].tolist()
pred=df['top1'].tolist()
print(len(pred))
print(len(gt))
print(gt[157])
# print(pred[801])
# print(df.head)

300
300
ambulance

In [183]:
score_list = []
score=0
gt_label = label_category(gt[0])

for i in range(len(pred)):
    gt_label = label_category(gt[i])
# #     print(gt[i])
#     if gt[i] == 'amusement_arcade':
#         print('1')
        
    pred_label = label_category(pred[i])
#     print("number : %i" %i)
#     print(gt_label)
#     print(pred_label)
    if pred_label =='None' :
        print("check")
    if gt_label == pred_label :
        score=1
    else :
        score=0
#     print(score)
    score_list.append(score)
print(len(score_list))

accuracy = sum(score_list) / len(score_list)
print(accuracy)

300
0.08666666666666667